version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///app/database/data/verres.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PYTHONPATH=/app
    volumes:
      - ./database/data:/app/database/data
      - ./model:/app/model
      - ./model/models:/app/model/models
      - ./model/templates:/app/model/templates
      - ./model/debug:/app/model/debug
    networks:
      - engravedetect-network

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - engravedetect-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - api
    networks:
      - engravedetect-network

volumes:
  redis_data:

networks:
  engravedetect-network:
    driver: bridge 