"""ajout tables symboles_tags et verres_symboles

Revision ID: a308ce07d0e4
Revises: 2edf1ef5ef75
Create Date: 2025-02-17 12:35:10.284410+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a308ce07d0e4"
down_revision: Union[str, None] = "2edf1ef5ef75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
