"""ajout tables symboles_tags et verres_symboles

Revision ID: 2edf1ef5ef75
Revises:
Create Date: 2025-02-17 12:27:45.262746+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2edf1ef5ef75"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "symboles_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nom", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nom"),
    )
    op.create_index("idx_symboles_nom", "symboles_tags", ["nom"], unique=False)
    op.create_table(
        "verres_symboles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("verre_id", sa.Integer(), nullable=False),
        sa.Column("symbole_id", sa.Integer(), nullable=False),
        sa.Column("score_confiance", sa.Float(), nullable=False),
        sa.Column("est_valide", sa.Boolean(), nullable=True),
        sa.Column("valide_par", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbole_id"],
            ["symboles_tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verre_id"],
            ["verres.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_verres_symboles_score",
        "verres_symboles",
        ["score_confiance"],
        unique=False,
    )
    op.create_index(
        "idx_verres_symboles_symbole_id",
        "verres_symboles",
        ["symbole_id"],
        unique=False,
    )
    op.create_index(
        "idx_verres_symboles_verre_id", "verres_symboles", ["verre_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_verres_symboles_verre_id", table_name="verres_symboles")
    op.drop_index("idx_verres_symboles_symbole_id", table_name="verres_symboles")
    op.drop_index("idx_verres_symboles_score", table_name="verres_symboles")
    op.drop_table("verres_symboles")
    op.drop_index("idx_symboles_nom", table_name="symboles_tags")
    op.drop_table("symboles_tags")
    # ### end Alembic commands ###
